# Generated by Django 6.0.7 on 2026-08-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('music_type', models.CharField(choices=[('song', 'Song'), ('beat', 'Beat'), ('demo', 'Demo')], max_length=20)),
                ('genre', models.CharField(choices=[('afrobeats', 'Afrobeats'), ('hiphop', 'Hip Hop'), ('rnb', 'R&B'), ('pop', 'Pop'), ('gospel', 'Gospel'), ('dancehall', 'Dancehall'), ('amapiano', 'Amapiano'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to='music/audio/')),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='music/artwork/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('plays', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
