# Generated by Django 6.0.7 on 2026-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at'], 'permissions': [('upload_music', 'Can upload music'), ('edit_own_music', 'Can edit own music'), ('delete_own_music', 'Can delete own music'), ('manage_beats', 'Can manage beats')]},
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
