# Generated by Django 4.1 on 2026-08-17 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='artists/avatars/'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/covers/'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
