# Generated by Django 4.1 on 2026-08-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artistprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
