# Generated by Django 4.1 on 2026-08-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_remove_comment_music_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
    ]
