# Generated by Django 4.1 on 2026-08-17 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producerprofile',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='studio_name',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='producers/avatars/'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='producers/covers/'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 17, 0, 33, 50, 606434, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='stage_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
