# Generated by Django 6.0.7 on 2026-08-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_rename_followers_producerprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
