# Generated by Django 6.0.7 on 2026-08-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_producerprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='stage_name',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='twitter',
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='professional_title',
            field=models.CharField(default='Music Producer / Director', max_length=150),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='producers/profile/'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='skill_description',
            field=models.TextField(blank=True, help_text='Example: Music Composition, Audio Production & Sound Design'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='software',
            field=models.TextField(blank=True, help_text='Example: Ableton Live, Cubase, Adobe Premiere, Logic Pro'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ProducerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('produced', 'Produced, Composed and Recorded'), ('directed', 'Directed Music and Audio')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='producers.producerprofile')),
            ],
            options={
                'ordering': ['display_order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProducerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='producers.producerprofile')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
