# Generated by Django 4.1 on 2026-08-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0005_alter_producerprofile_id_alter_producerproject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producerproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producerskill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
