# Generated by Django 4.1 on 2026-08-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0006_alter_producerprofile_id_alter_producerproject_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/covers/'),
        ),
    ]
