# Generated by Django 4.1 on 2026-08-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0007_producerprofile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='producer/covers/'),
        ),
    ]
