# Generated by Django 6.0.7 on 2026-09-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_audio_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_start',
            field=models.FloatField(default=0),
        ),
    ]
