# Generated by Django 4.1 on 2026-08-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_alter_beat_id_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
