# Generated by Django 6.0.7 on 2026-08-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_alter_collaboration_id_alter_follow_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
