# Generated by Django 6.0.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collaborations",
            "0003_remove_follow_unique_follow_delete_follow",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [

        migrations.AlterModelOptions(
            name="collaboration",
            options={
                "permissions": [
                    (
                        "send_collaboration",
                        "Can send collaboration requests",
                    ),
                    (
                        "manage_collaboration",
                        "Can manage collaborations",
                    ),
                ],
            },
        ),

        migrations.RemoveField(
            model_name="collaboration",
            name="receiver",
        ),

        migrations.RemoveField(
            model_name="collaboration",
            name="sender",
        ),

        migrations.AddField(
            model_name="collaboration",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddField(
            model_name="collaboration",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="producer_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddField(
            model_name="collaboration",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True
            ),
        ),

        migrations.AlterField(
            model_name="collaboration",
            name="message",
            field=models.TextField(
                blank=True
            ),
        ),
    ]