# Generated by Django 4.1 on 2026-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0004_alter_collaboration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
