# Generated by Django 4.1 on 2026-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0006_alter_collaboration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='title',
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
