# Generated by Django 6.0.7 on 2026-08-31 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0007_remove_collaboration_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboration',
            options={'ordering': ['-created_at'], 'permissions': [('send_collaboration', 'Can send collaboration requests'), ('manage_collaboration', 'Can manage collaborations')]},
        ),
        migrations.AddField(
            model_name='collaboration',
            name='project_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='artist',
            field=models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='artist_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='producer',
            field=models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='producer_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
